-- Catálogo inicial de interesses (idempotente — usa unique (category, name))

insert into interests (category, name, sort_order) values
  -- Esportes
  ('Esportes','Tênis',10),
  ('Esportes','Beach Tennis',11),
  ('Esportes','Padel',12),
  ('Esportes','Futebol',13),
  ('Esportes','Vôlei',14),
  ('Esportes','Basquete',15),
  ('Esportes','Natação',16),
  ('Esportes','Hidroginástica',17),
  ('Esportes','Corrida',18),
  ('Esportes','Ciclismo',19),
  ('Esportes','Skate',20),
  ('Esportes','Yoga',21),
  ('Esportes','Pilates',22),
  ('Esportes','Funcional',23),
  ('Esportes','Crossfit',24),
  ('Esportes','Muay Thai',25),
  ('Esportes','Jiu-Jitsu',26),
  ('Esportes','Boxe',27),
  ('Esportes','Karatê',28),
  ('Esportes','Judô',29),
  ('Esportes','Ballet',30),
  ('Esportes','Dança',31),
  ('Esportes','Ginástica olímpica',32),
  ('Esportes','Escalada',33),
  -- Música
  ('Música','Violão',40),
  ('Música','Piano',41),
  ('Música','Bateria',42),
  ('Música','Canto',43),
  ('Música','Teclado',44),
  ('Música','Guitarra',45),
  ('Música','Baixo',46),
  ('Música','Ukulele',47),
  ('Música','Coral',48),
  ('Música','Banda em conjunto',49),
  -- Artes e Manualidades
  ('Artes e Manualidades','Pintura',60),
  ('Artes e Manualidades','Desenho',61),
  ('Artes e Manualidades','Cerâmica',62),
  ('Artes e Manualidades','Costura',63),
  ('Artes e Manualidades','Tricô e Crochê',64),
  ('Artes e Manualidades','Marcenaria',65),
  ('Artes e Manualidades','Fotografia',66),
  -- Bem-estar
  ('Bem-estar','Meditação',80),
  ('Bem-estar','Mindfulness',81),
  ('Bem-estar','Reiki',82),
  ('Bem-estar','Terapia em grupo',83),
  -- Idiomas
  ('Idiomas','Inglês',100),
  ('Idiomas','Espanhol',101),
  ('Idiomas','Francês',102),
  ('Idiomas','Italiano',103),
  ('Idiomas','Mandarim',104),
  ('Idiomas','Libras',105),
  -- Tecnologia
  ('Tecnologia','Programação para crianças',120),
  ('Tecnologia','Robótica',121),
  ('Tecnologia','Eletrônica e Maker',122),
  -- Jogos e Lazer
  ('Jogos e Lazer','Xadrez',140),
  ('Jogos e Lazer','Pôquer',141),
  ('Jogos e Lazer','RPG',142),
  ('Jogos e Lazer','Boardgames',143),
  ('Jogos e Lazer','Videogame em grupo',144),
  -- Leitura e Estudo
  ('Leitura e Estudo','Clube do livro',160),
  ('Leitura e Estudo','Grupo de estudos',161),
  ('Leitura e Estudo','Filosofia',162),
  ('Leitura e Estudo','História da arte',163),
  -- Culinária
  ('Culinária','Confeitaria',180),
  ('Culinária','Cozinha vegetariana',181),
  ('Culinária','Vinhos',182),
  ('Culinária','Cervejas artesanais',183),
  -- Social
  ('Social','Happy hour',200),
  ('Social','Cinema em grupo',201),
  ('Social','Caminhada e trilha',202),
  ('Social','Voluntariado',203)
on conflict (category, name) do nothing;
