-- ============================================================================
-- 0004 — Expansão do catálogo (~120 novos itens, +Dança, +Família e Bebê, +Fitness)
-- ============================================================================

-- Mover Dança/Ballet de Esportes pra categoria própria. Como N:N tem ON DELETE
-- CASCADE, deletar a interest remove referências (era zero em fresh DB).
delete from interests where category = 'Esportes' and name in ('Dança','Ballet');

insert into interests (category, name, sort_order) values
  -- Esportes (expansão)
  ('Esportes','Squash',34),
  ('Esportes','Pickleball',35),
  ('Esportes','Frescobol',36),
  ('Esportes','Futsal',37),
  ('Esportes','Futebol society',38),
  ('Esportes','Futevôlei',39),
  ('Esportes','Vôlei de praia',300),
  ('Esportes','Handball',301),
  ('Esportes','Pólo aquático',302),
  ('Esportes','Caminhada',303),
  ('Esportes','Trail running',304),
  ('Esportes','Mountain bike',305),
  ('Esportes','Ciclismo de estrada',306),
  ('Esportes','Patinação',307),
  ('Esportes','Patins',308),
  ('Esportes','Power Pilates',309),
  ('Esportes','HIIT',310),
  ('Esportes','Musculação',311),
  ('Esportes','Taekwondo',312),
  ('Esportes','Kung Fu',313),
  ('Esportes','Capoeira',314),
  ('Esportes','MMA',315),
  ('Esportes','Acrobacia',316),
  ('Esportes','Parkour',317),
  ('Esportes','Boulder',318),
  ('Esportes','Surf',319),
  ('Esportes','Stand Up Paddle',320),
  ('Esportes','Kitesurf',321),
  ('Esportes','Golfe',322),
  ('Esportes','Tiro com arco',323),
  ('Esportes','Esgrima',324),
  ('Esportes','Equitação',325),
  -- Dança (nova categoria)
  ('Dança','Ballet',400),
  ('Dança','Ballet adulto',401),
  ('Dança','Jazz',402),
  ('Dança','Sapateado',403),
  ('Dança','Dança contemporânea',404),
  ('Dança','Hip Hop',405),
  ('Dança','Street Dance',406),
  ('Dança','K-pop',407),
  ('Dança','Funk',408),
  ('Dança','Forró',409),
  ('Dança','Samba',410),
  ('Dança','Pagode',411),
  ('Dança','Zouk',412),
  ('Dança','Bolero',413),
  ('Dança','Salsa',414),
  ('Dança','Bachata',415),
  ('Dança','Merengue',416),
  ('Dança','Kizomba',417),
  ('Dança','Tango',418),
  ('Dança','Dança do ventre',419),
  ('Dança','Flamenco',420),
  ('Dança','Zumba',421),
  ('Dança','FitDance',422),
  ('Dança','Pole dance',423),
  -- Música — instrumentos (expansão)
  ('Música','Cavaquinho',500),
  ('Música','Acordeon',501),
  ('Música','Percussão',502),
  ('Música','Cajón',503),
  ('Música','Pandeiro',504),
  ('Música','Violino',505),
  ('Música','Viola',506),
  ('Música','Violoncelo',507),
  ('Música','Contrabaixo acústico',508),
  ('Música','Saxofone',509),
  ('Música','Trompete',510),
  ('Música','Trombone',511),
  ('Música','Flauta transversal',512),
  ('Música','Flauta doce',513),
  ('Música','Clarinete',514),
  ('Música','Harmônica / Gaita',515),
  ('Música','Bandolim',516),
  ('Música','Harpa',517),
  ('Música','DJ',518),
  ('Música','Produção musical',519),
  -- Bem-estar (expansão)
  ('Bem-estar','Yin yoga',600),
  ('Bem-estar','Yoga restaurativo',601),
  ('Bem-estar','Cromoterapia',602),
  ('Bem-estar','Aromaterapia',603),
  ('Bem-estar','Astrologia',604),
  ('Bem-estar','Tarô',605),
  ('Bem-estar','Constelação familiar',606),
  ('Bem-estar','Nutrição',607),
  ('Bem-estar','Ayurveda',608),
  -- Idiomas (expansão)
  ('Idiomas','Alemão',700),
  ('Idiomas','Japonês',701),
  ('Idiomas','Coreano',702),
  ('Idiomas','Russo',703),
  ('Idiomas','Árabe',704),
  ('Idiomas','Hebraico',705),
  ('Idiomas','Português para estrangeiros',706),
  ('Idiomas','Latim',707),
  ('Idiomas','Holandês',708),
  -- Tecnologia (expansão)
  ('Tecnologia','Programação para iniciantes',800),
  ('Tecnologia','Arduino',801),
  ('Tecnologia','Raspberry Pi',802),
  ('Tecnologia','IA / Machine Learning',803),
  ('Tecnologia','Cybersegurança',804),
  ('Tecnologia','Edição de vídeo',805),
  ('Tecnologia','Edição de foto',806),
  ('Tecnologia','Modelagem 3D',807),
  ('Tecnologia','Impressão 3D',808),
  ('Tecnologia','Game design',809),
  -- Artes (expansão)
  ('Artes e Manualidades','Aquarela',900),
  ('Artes e Manualidades','Ilustração digital',901),
  ('Artes e Manualidades','Quadrinhos',902),
  ('Artes e Manualidades','Escultura',903),
  ('Artes e Manualidades','Bordado',904),
  ('Artes e Manualidades','Patchwork',905),
  ('Artes e Manualidades','Macramê',906),
  ('Artes e Manualidades','Joalheria',907),
  ('Artes e Manualidades','Bijuteria',908),
  ('Artes e Manualidades','Origami',909),
  ('Artes e Manualidades','Caligrafia',910),
  ('Artes e Manualidades','Lettering',911),
  ('Artes e Manualidades','Restauração de móveis',912),
  ('Artes e Manualidades','Filmagem',913),
  ('Artes e Manualidades','Cerâmica em torno',914),
  -- Jogos (expansão)
  ('Jogos e Lazer','Damas',1000),
  ('Jogos e Lazer','Gamão',1001),
  ('Jogos e Lazer','Truco',1002),
  ('Jogos e Lazer','Buraco',1003),
  ('Jogos e Lazer','Canastra',1004),
  ('Jogos e Lazer','Magic / Card games',1005),
  ('Jogos e Lazer','Sinuca / Bilhar',1006),
  ('Jogos e Lazer','Dominó',1007),
  -- Leitura/Estudo (expansão)
  ('Leitura e Estudo','Cinema (clube)',1100),
  ('Leitura e Estudo','Escrita criativa',1101),
  ('Leitura e Estudo','Poesia',1102),
  ('Leitura e Estudo','História',1103),
  ('Leitura e Estudo','Astronomia',1104),
  -- Culinária (expansão)
  ('Culinária','Panificação',1200),
  ('Culinária','Cozinha brasileira',1201),
  ('Culinária','Cozinha italiana',1202),
  ('Culinária','Cozinha asiática',1203),
  ('Culinária','Cozinha vegana',1204),
  ('Culinária','Churrasco',1205),
  ('Culinária','Massas',1206),
  ('Culinária','Sushi',1207),
  ('Culinária','Drinques / Cocktails',1208),
  ('Culinária','Café / Barista',1209),
  ('Culinária','Fermentação',1210),
  -- Social (expansão)
  ('Social','Acampamento',1300),
  ('Social','Pet meet (passear cães)',1301),
  ('Social','Quiz / Trivia',1302),
  -- Família e Bebê (nova categoria)
  ('Família e Bebê','Yoga pré-natal',1400),
  ('Família e Bebê','Yoga mamãe e bebê',1401),
  ('Família e Bebê','Musicalização infantil',1402),
  ('Família e Bebê','Estímulo precoce',1403),
  ('Família e Bebê','Grupo de gestantes',1404),
  ('Família e Bebê','Grupo de pais',1405),
  ('Família e Bebê','Encontros de famílias',1406),
  -- Fitness (nova categoria)
  ('Fitness','Spinning',1500),
  ('Fitness','Step',1501),
  ('Fitness','Aeróbica',1502),
  ('Fitness','Body Combat',1503),
  ('Fitness','Body Pump',1504)
on conflict (category, name) do nothing;
